//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAutomationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_In_Out
    {
        public int check_In_Out_Id { get; set; }
        public Nullable<int> member_Id { get; set; }
        public Nullable<System.DateTime> check_In_Date { get; set; }
        public Nullable<System.DateTime> check_Out_Date { get; set; }
        public Nullable<System.DateTime> lunch_break { get; set; }
        public Nullable<System.DateTime> lunch_break_End { get; set; }
    
        public virtual members members { get; set; }
    }
}
