//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAutomationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class excuse
    {
        public int excuse_Id { get; set; }
        public Nullable<int> member_Id { get; set; }
        public Nullable<System.DateTime> excuse_Date { get; set; }
        public string excuse_Text { get; set; }
    
        public virtual members members { get; set; }
    }
}
