//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAutomationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MemberAutomationEntities : DbContext
    {
        public MemberAutomationEntities()
            : base("name=MemberAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authority> authority { get; set; }
        public virtual DbSet<authorityMembers> authorityMembers { get; set; }
        public virtual DbSet<check_In_Out> check_In_Out { get; set; }
        public virtual DbSet<excuse> excuse { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<logType> logType { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<Months> Months { get; set; }
<<<<<<< HEAD
=======
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
>>>>>>> origin
    }
}
